### PR TITLE
the radial is now in sync with the percentage score

### PR DESCRIPTION
**Pull request by Codesmith28**

### CODE REVIEW

**Comment by JeelRajodiya** [comment]
## how will it handle negative marks? also round up the percentages
image
image

**Comment by Codesmith28** [comment]
for negative score there will be no radial
instead red tent 
I will work on the rounded part 👍

**Comment by JeelRajodiya** [comment]
## No difficulty tag is not set to Medium by default 
image

**Comment by Codesmith28** [comment]
Panik

**Review by JeelRajodiya — APPROVED** [review]

**Review by JeelRajodiya — APPROVED** [review]

**Review by JeelRajodiya — DISMISSED** [review]

**Comment by Codesmith28** [comment]
now it officially defaults the difficulty to medium !!!
please accept my pull request 😃🥞

**Comment by JeelRajodiya** [comment]
> now it officially defaults the difficulty to medium !!! please accept my pull request 😃🥞

Very good job. The default is now medium

**Comment by Codesmith28** [comment]
Please merge it for gods' sake....🥲

**Review by JeelRajodiya — APPROVED** [review]

**Pull request merged**
